### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by CD6-timury** [Info442-team-2/friendly-mvp#23]
**Describe the bug**
NavBar doesn't seem to be complete, which means you can't add a group, as well as currently clicking on the logo - redirects you to the page to login page.

**To Reproduce**
1. After you login, click on the navbar.

**Expected behavior**
Clicking on logo redirects to homepage.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Comment by anuraagpolisetty** [comment]
Navbar is now functional and redirects to the appropriate page
