### ISSUE TITLE
Can't press enter logging in

### ISSUE THREAD

**Issue by ccforbes** [Info442-team-2/friendly-mvp#35]
**Describe the bug**
Trying to login doesn't work when pressing enter

**To Reproduce**
1. Enter in valid login information
2. Press Enter

**Expected behavior**
When pressing enter with correct login information, the app should log me in.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

**Comment by KeithSRoberts** [comment]
This is not major, this was not a feature we had in mind for all users, only those who require a screenreader. If you use tabs and navigate to the button that way, the enter button should work. Thank you for the report though...

**Comment by ccforbes** [comment]
Hmm okay. I don't think I should be using tabs to navigate to the login button. Apps like Facebook allows us to hit enter without needing to navigate explicitly to the "login" button. It's automatically assumed. It's a usability issue.

**Comment by KeithSRoberts** [comment]
Are we an app like Facebook? No, we aren’t, and I don’t expect apps like Facebook to define what every app should have. We can agree to disagree on this one.
