### ISSUE TITLE
Seeing people's passwords

### ISSUE THREAD

**Issue by anantr98** [Info442-team-2/friendly-mvp#37]
**Describe the bug**
I hate to call this a major issue because I think it's an easy fix, but if you click on someone's profile inside the application, you can literally see their password by hovering over the element when inspecting it in Google Chrome or Safari. 

**To Reproduce**
1. Go to the user's profile by clicking on their profile username in a group
2. Click on "inspect element"
3. Where the password is located in the HTML, you can see the "value" which is their password. 

**Expected behavior**
Not being able to see other people's passwords

**Screenshots**

**Desktop (please complete the following information):**
Chrome/Safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lockheedmartian** [comment]
Fixed in e77210e
