### ISSUE TITLE
Friend.ly logo doesn't bring you back to all groups if you search for something beforehand

### ISSUE THREAD

**Issue by ssunni12** [Info442-team-2/friendly-mvp#39]
**Describe the bug**
After searching for a particular group (in this case the Baljeet Fan Club) and then clicking 'My Profile' and then clicking the main Friend.ly icon in the top left part of the screen, it only returns you back to the groups that showed up when you searched. All of the other groups are not shown and there is no way to get them back. It seems like you are only limited to the groups that you have searched for.

**To Reproduce**
1. Search for a particular group (like 'Baljeet')
2. Click on 'My Profile'
3. Click on the Friend.ly icon

**Expected behavior**
To see all of the groups after clicking the Friend.ly icon, as in it is supposed to bring you back to the main dashboard.

**Desktop (please complete the following information):**
-Chrome on Windows 10

**Comment by KeithSRoberts** [comment]
Fixed by https://github.com/Info442-team-2/friendly-mvp/commit/1f01bd7022c45f42238097e4991a1f900359de8d
