### ISSUE TITLE
[minor] altering your password but not actually altering it in the database

### ISSUE THREAD

**Issue by anantr98** [Info442-team-2/friendly-mvp#40]
**Describe the bug**
You can like type inside your "password" area in your profile

**To Reproduce**
1. Go to your profile by clicking on your name in a discussion in a group
2. Click on your password field
3. You can type in it and change it around. I dont' think it actually changes your password but might just be a weird feature. 

**Expected behavior**
Not seeing password 

**Screenshots**

**Desktop (please complete the following information):**
Chrome/Safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KeithSRoberts** [comment]
Are clicking the “save changes” button at the bottom of the page after you modify your password?

**Comment by KeithSRoberts** [comment]
Are you clicking on the “save changes” button at the bottom of the page after you change the password input?

**Comment by anantr98** [comment]
Ohhh! I see it now - it's a password change feature. Gotcha. I wasn't sure if it was supposed to be like that - (maybe add something to say that you are able to change it?)

**Comment by KeithSRoberts** [comment]
Thanks for you feedback, we’ll definitely try to make it more apparent that the fields are editable in your profile page. Leaving this open for now until we do so

**Comment by lockheedmartian** [comment]
Fixed in e77210e
