### ISSUE TITLE
Password seen in chrome when doing inspect

### ISSUE THREAD

**Issue by tran6388-1672747** [Info442-team-2/friendly-mvp#43]
**Describe the bug**
I have seen one person already report this as an major issue, so I will not write this as major issue. But, I really hope you guy can fix this bug. I can see other people password by going to the profile and click inspect in chrome. Please fix this bug because this is a major security issue.

**To Reproduce**
1. Go to "https://info442-team-2.github.io/friendly-mvp/#/account/28"
2. Click on inspect on chrome
3. Scroll down to:
<div id="profileInputWrapper"><input id="account-username" placeholder="Username" type="text" class="profile-input form-control" value="tran6388"><input id="account-password" placeholder="Password" type="password" class="profile-input form-control" value="kimkim6388"></div>
4. See error: show my password.

**Expected behavior**
Hide this password when the user click inspects in chrome.

**Screenshots**
![Screenshot (60)](https://user-images.githubusercontent.com/23422230/70338553-04ef1500-1802-11ea-8fc5-c5e5b6e724b6.png)

**Desktop (please complete the following information):**
 - Browser: chrome

**Additional context**

**Comment by lockheedmartian** [comment]
Duplicate of #37
