### ISSUE TITLE
Can enter post with invalid or meaningless characters.

### ISSUE THREAD

**Issue by tran6388-1672747** [Info442-team-2/friendly-mvp#44]
**Describe the bug**
I know that this is a very difficult thing to fix, but when creating new group, I can enter meaningless characters like "__" or "=". I don't think there is quick way to fix this. I just hope you guy can find a way.

**To Reproduce**
1. Go to create group
2. Enter all field with "_" or "+" or "="
3. Click "Create Group"
4. See error page in the screenshot.

**Expected behavior**
do a check if the text is meaning full.

**Screenshots**
![Screenshot (61)](https://user-images.githubusercontent.com/23422230/70339367-91e69e00-1803-11ea-8b6c-14627185acfd.png)

**Desktop (please complete the following information):**
 - Browser: chrome

**Additional context**

**Comment by KeithSRoberts** [comment]
Fixed by  https://github.com/Info442-team-2/friendly-mvp/commit/613e95c20f4017401463bee2fdc8771d6d8109e1
