### ISSUE TITLE
Refreshing the page brings you back to the login instead of same page

### ISSUE THREAD

**Issue by wochen96** [Info442-team-2/friendly-mvp#47]
**Describe the bug**
Refreshing the page brings you back to the login instead of same page

**To Reproduce**
1. Login
2. Go to the dashboard
3. Refresh page

**Expected behavior**
I should be able to stay on the same page without having to login again.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by lockheedmartian** [comment]
This is because when your refresh the page, you actually are logging yourself out and have to login again. We understand that this can be frustrating, but to fix this we will have to redo our entire authentication logic (which is out of scope at this stage in the project).
