### ISSUE TITLE
Empty title and text for creating group

### ISSUE THREAD

**Issue by albertli354** [Info442-team-2/friendly-mvp#48]
**Describe the bug**
The website allows me to create a group with an empty title and text. I think it is better to require users to enter something in order to create a meaningful group. A group with an empty title and description does not make any sense for me. 

**To Reproduce**
1. Click "create new group"
2. Click the image to upload an image url
3. Click load image
4. Click confirm
5. Enter empty space for title and text
6. New group created

**Expected behavior**
The website should check whether users entered empty for group title and description, and alter users if they choose to create an empty group.

**Screenshots**
![image](https://user-images.githubusercontent.com/26781751/70367259-3217e380-1853-11ea-876f-37c4baa56675.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Comment by KeithSRoberts** [comment]
Fixed by https://github.com/Info442-team-2/friendly-mvp/commit/613e95c20f4017401463bee2fdc8771d6d8109e1
