### ISSUE TITLE
Users aren't able to save interests

### ISSUE THREAD

**Issue by Kyrabautista** [Info442-team-2/friendly-mvp#49]
**Describe the bug**
Users aren't able to save their interests. After coming back from another tab or refreshing the game, Interests information is not displayed

**To Reproduce**
1. Go to "My Profile"
2. Scroll down to the "interest section"
3. Type in an interest in the interest section
4. scroll down and click on "save changes"
5.) Refresh page
6.) Scroll down to the "Interests" section and you'll see that your changes weren't saved.
 
**Expected behavior**
I expected that when clicking on "saved changes" that my response will be recorded and displayed in "My profile".

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 18362.476
 - Browser Chrome
 - Version 78.0.3904.108

**Comment by lockheedmartian** [comment]
After you typed in an interest, did you press "Enter"? (The placeholders in the input fields say to press "Enter" to submit an interest

**Comment by Kyrabautista** [comment]
lol my baddd. It works!
I honestly didn't notice because I assumed "save changes" would automatically save everything.
I think I scrolled down too fast towards "save changes" at the bottom to notice that my inputs didn't get recorded.
