### ISSUE TITLE
Search bar text

### ISSUE THREAD

**Issue by laurens24** [Info442-team-2/friendly-mvp#50]
**Describe the bug**
On any of the pages, the placeholder text within the search bar is cut off at the end (this is very minor)

**To Reproduce**
1. Open any of the pages within the site 

**Expected behavior**
To be able to see the search text, assuming it's supposed to say "Look for groups"

**Screenshots**
![image](https://user-images.githubusercontent.com/13319713/70383086-b7b39600-191c-11ea-96b0-9b0641f08d6a.png)

**Desktop (please complete the following information):**
 - Macbook Pro 13 inch screen
 - Google Chrome

**Comment by yrkim98** [comment]
The searchbar placeholder now is visible for many all desktop screen sizes.
