### ISSUE TITLE
[Minor] Unclear signup experience

### ISSUE THREAD

**Issue by sauravkh** [Info442-team-2/friendly-mvp#51]
**Describe the bug**
At the home page, as a first time user I would click the signup button first since I don't yet have credentials. The homepage currently has *one* form for both signup and signing which makes the signup experience confusing. 

**To Reproduce**
1. Go to homepage
2. There is only one form for sign-up and sign-in without clear identifiers. 

**Expected behavior**
The signup button could either be separate or have a new form when clicked on 'sign-up' button without forcing me to enter credentials into the sign-in box. 

**Screenshots**
[
<img width="642" alt="Screen Shot 2019-12-09 at 1 24 14 AM" src="https://user-images.githubusercontent.com/18123287/70423598-a6ed4800-1a22-11ea-834c-ea27270d01cb.png">
](url)

**Comment by lockheedmartian** [comment]
This isn't a bug. Given the time we have in this class, implementing a substantial change to our registration process is out of scope. I'm closing this issue.
