### ISSUE TITLE
[minor] UX issue

### ISSUE THREAD

**Issue by 3ickey** [Info442-team-2/friendly-mvp#56]
**Describe the bug**
When entering video games interests and I click away from the input field, it clears the input field and I have to write again.

**To Reproduce**
1. Go to 'Sign Up and enter details to sing up'
2. Click on 'Games Icon' to select interest 
3. Start typing insert in the input field and click away anywhere on the screen
4. See error where the input field clears itself 

**Expected behavior**
I expect the input field to hold the value when a click away from it or go to another tab and come back to it.

**Desktop**
 - Accessed from 27" external monitor
 - OS: macOS
 - Browser: Safari

**Comment by lockheedmartian** [comment]
The input fields require you to press the enter key when adding interests and each input field has placeholder text that says this explicitly. Marking this issue as resolved.
