### ISSUE TITLE
Cannot view all tags of an interest in profile page

### ISSUE THREAD

**Issue by alexh5** [Info442-team-2/friendly-mvp#57]
**Describe the bug**
If a user's interest has many tags, there is no way to see all of them on the profile page.

**To Reproduce**
1. Login to the app.
2. Click on "My Profile".
3. Click on the textbox for the Music Interest.
4. Create 10 different tags.
5. Attempt to view each tag that was just created.

**Expected behavior**
There should be a way to view all of the tags under each interest, whether that be displaying all of them or allowing the user to scroll through each textbox.

**Screenshots**
![interest1](https://user-images.githubusercontent.com/32464069/70475290-1d249580-1a89-11ea-8e8e-b062f4a16d9b.PNG)
![interest2](https://user-images.githubusercontent.com/32464069/70475298-1f86ef80-1a89-11ea-92b8-cb1ecf295301.PNG)

The only way to view hidden tags is by deleting other tags, which is a problem if the user wants to keep the displayed tags.

**Comment by lockheedmartian** [comment]
Are you able to scroll horizontally through the input field? You should be able to

**Comment by lockheedmartian** [comment]
Added scrollbars for clarity in 672e758
